/**
 * BaseService — HTTP client base
 * Auto-generated by create-web-arch
 *
 * Uses TanStack Query for caching and async state management.
 */

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL ?? "";

class HttpError extends Error {
  constructor(
    public status: number,
    message: string
  ) {
    super(message);
    this.name = "HttpError";
  }
}

async function request<T>(
  endpoint: string,
  options?: RequestInit
): Promise<T> {
  const res = await fetch(`${BASE_URL}${endpoint}`, {
    headers: { "Content-Type": "application/json" },
    ...options,
  });

  if (!res.ok) {
    throw new HttpError(res.status, `HTTP ${res.status}: ${res.statusText}`);
  }

  return res.json() as Promise<T>;
}

export const http = {
  get:    <T>(url: string)                    => request<T>(url),
  post:   <T>(url: string, body: unknown)     => request<T>(url, { method: "POST",   body: JSON.stringify(body) }),
  put:    <T>(url: string, body: unknown)     => request<T>(url, { method: "PUT",    body: JSON.stringify(body) }),
  patch:  <T>(url: string, body: unknown)     => request<T>(url, { method: "PATCH",  body: JSON.stringify(body) }),
  delete: <T>(url: string)                    => request<T>(url, { method: "DELETE" }),
};

export { HttpError };
